version: "2"
run:
  timeout: 5m
linters:
  enable:
    - revive
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errcheck
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
          exclude: [""]

