executor:
  shell: /bin/bash
services:
  date: "date"
  volume0: totalmixrelay -v 0.0
  volume1: totalmixrelay -v 0.05
  volume2: totalmixrelay -v 0.10
  volume3: totalmixrelay -v 0.15
  volume4: totalmixrelay -v 0.20
  volume5: totalmixrelay -v 0.25
  volume6: totalmixrelay -v 0.30
  volume7: totalmixrelay -v 0.35
  volume8: totalmixrelay -v 0.40
  volume9: totalmixrelay -v 0.45
  volume10: totalmixrelay -v 0.5
http:
  enabled: true
mqtt:
  enabled: true
  user: whatever
  pass: whatever
  address: tcp://127.0.0.1:1883
  topic: /mqttrooper/b
