#!/usr/bin/env bash

archs=("amd64" "arm64")
oss=("darwin" "linux")
cmds=("mqttrooper" "mqttrooper-publisher" "mqttrooper-services")

cat <<EOF
#
# Code generated by gen-makefile.sh. DO NOT EDIT
#   Generated at: $(date "+%Y-%m-%d %H:%I:%S")
#

EOF
cat <<EOF
.PHONY: all
all: setup dist $(for i in "${oss[@]}"; do echo -n "$i "; done)

EOF

# Targets for every os. E.g. make darwin, make linux
for os in "${oss[@]}" ; do
cat <<EOF
.PHONY: $os
$os: setup dist $(for arch in "${archs[@]}"; do for cmd in "${cmds[@]}"; do echo -n "dist/$cmd.$os.$arch "; done; done)

EOF

done

# Executables for all platforms and achitectures
GO_FLAGS='-ldflags "-s -w"'
for os in "${oss[@]}"; do
    for arch in "${archs[@]}"; do
        for cmd in "${cmds[@]}"; do
            cat <<EOF
dist/$cmd.$os.$arch: cmd/$cmd/main.go $(find . -iname "*.go" -or -iname "*.tmpl" | tr -s "\n" " ")
	GOARCH=$arch GOOS=$os go build $GO_FLAGS -o \$@ \$<

EOF
        done
    done
done

cat <<EOF
.PHONY: archive
archive: all $(for os in "${oss[@]}"; do for arch in "${archs[@]}"; do echo -n "dist/mqttrooper.$os.$arch.tgz " ;done; done)

EOF

# Targets for the archives
for os in "${oss[@]}"; do
    for arch in "${archs[@]}"; do
        cat <<EOF
dist/mqttrooper.$os.$arch.tgz:
	tar -cvzf \$@ dist/*.$os.$arch

EOF
    done
done
